/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.freebeachler.android.demos.component.slideshow;

public final class R {
    public static final class attr {
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int startIndex=0x7f010000;
    }
    public static final class drawable {
        public static final int arrow_left=0x7f020000;
        public static final int arrow_right=0x7f020001;
        public static final int eclipse_from_moon=0x7f020002;
        public static final int halebopp=0x7f020003;
        public static final int icon=0x7f020004;
        public static final int new_zeal=0x7f020005;
    }
    public static final class id {
        public static final int butt_slide_main_next=0x7f050003;
        public static final int butt_slide_main_prev=0x7f050001;
        public static final int content_wrap_slideshow=0x7f050000;
        public static final int slide_show=0x7f050002;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int header=0x7f040001;
        public static final int label_slide_anim_end=0x7f040005;
        public static final int label_slide_anim_start=0x7f040004;
        public static final int label_ss_load_end=0x7f040003;
        public static final int label_ss_load_start=0x7f040002;
    }
    public static final class styleable {
        /** Attributes that can be used with a SlideShow.
           <p>Includes the following attributes:</p>
           <table border="2" width="85%" align="center" frame="hsides" rules="all" cellpadding="5">
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute<th>Summary</tr>
           <tr><th><code>{@link #SlideShow_startIndex com.freebeachler.android.demos.component.slideshow:startIndex}</code><td></tr>
           </table>
           @see #SlideShow_startIndex
         */
        public static final int[] SlideShow = {
            0x7f010000
        };
        /**
          <p>This symbol is the offset where the {@link com.freebeachler.android.demos.component.slideshow.R.attr#startIndex}
          attribute's value can be found in the {@link #SlideShow} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:startIndex
        */
        public static final int SlideShow_startIndex = 0;
    };
}
